name: Generate project pages from project issues

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]

jobs:
  issue_to_page:
    if: github.repository_owner == 'brainhackorg'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade --user pip
        pip install -r requirements.txt
        python --version
        pip --version
        pip list

    - name: Run script to generate separate pages from issues
      run: |
        url="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues?per_page=100"
        path="content/project"
        echo "Project issues URL: "
        echo $url
        echo "Project pages destination directory: "
        echo $path
        transform_issues_to_pages.py $url $path

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: publish-project
        delete-branch: true
        commit-message: Convert issues to project pages, yay!
        title: '[ENH] Convert issues to project pages'
        body: 'done via this [GitHub Action](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/.github/workflows/issue-to-page.yml)'
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
