name: "Label from issue first message body"
# See https://github.com/marketplace/actions/regex-issue-labeler

on:
  issues:
    types: [opened, edited]

jobs:
  labeller:
    if: github.repository_owner == 'brainhackorg'
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.3
        with:
          # Secret token needed (not sure which permisions though)
          repo-token: ${{ github.token }}
          # File with label/regex match dictionary
          configuration-path: .github/labeler.yml
          # This can be increased if the dictionary undergoes a breaking change
          enable-versioned-regex: 0
